title: Sagun Garg
description: 3 x Founder/CTO (12yrs), 3 x EIR, Polyglot Programmer, ex-Deloitte, B-Tech(CS).
baseurl: "/"
url: "https://sagungargs15.github.io"
show_downloads: false
google_analytics: UA-175512960-1
theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate # Rename index.md to index.html. Without this, the jekyll-paginate gem will not work.
  - jekyll-feed # 
  - jemoji # Uncomment this to allow emoji in your post

# Author
author:
  name: Sagun Garg
  url: https://sagungarg.com
  email: sagungargs@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Disqus (Set to your disqus id)
disqus: jekyll-tale

gems: 
  - jekyll-github-metadata